version: '3'

services:
  redis:
    build:
      context: .
      dockerfile: ./dockerfile/redis
    container_name: redis

  elasticsearch:
    build:
      context: .
      dockerfile: ./dockerfile/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    container_name: elasticsearch

  db:
    build:
      context: .
      dockerfile: ./dockerfile/db
    environment:
      - MYSQL_DATABASE=yolo
      - MYSQL_USER=yolo
      - MYSQL_PASSWORD=yolo
      - MYSQL_ROOT_PASSWORD=root
    container_name: db

  phpmyadmin:
    build:
      context: .
      dockerfile: ./dockerfile/phpmyadmin
    links:
      - db
    container_name: phpmyadmin

  nginx:
    build:
      context: .
      dockerfile: ./dockerfile/nginx
    links:
      - phpmyadmin
      - elasticsearch
    ports:
      - 80:80
      - 443:443
    container_name: nginx
